#headless service,normol service ,statefulset
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense
  labels:
    app: mysql
    project: expense
    tier: db
spec:
  clusterIP: None
  selector:
    app: mysql
    project: expense
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
kind: Service
apiVersion: v1
metadata: 
  name: mysql
  namespace: expense
spec:
  selector:
    app: mysql
    project: expense
    tier: db   
  ports:
  - protocol: TCP
    port: 3306 #service port
    targetPort: 3306